<?php 
// @todo: this in init head maybe?

$this->emerald()->addEverything();

$this->headMeta()->appendName("description", "Mikko Forsström's home page");
$this->headMeta()->appendName("Author", "Mikko Forsström");
$this->headMeta()->appendName("Content-Language", "en");

$this->headTitle()->setSeparator(' - ');

?>

<?php echo $this->doctype('XHTML1_TRANSITIONAL'); ?>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<?php echo $this->headMeta(); ?>
<?php print $this->headTitle(); ?>
<?php echo $this->headLink(); ?>
</head>

<body>
<div id="wrapper">

<div id="header">
	<div id="logo">
		<h1><a href="<?php echo URL_BASE; ?>/">Emerald<sup></sup></a></h1>
		<h2>Content management built upon Zend Framework</h2>
	</div>
	<div id="menu">
	<?php echo $this->navigation()->menu()->renderMenu(null, array('minDepth' => 0, 'maxDepth' => 0, 'onlyActiveBranch' => false)); ?>
	</div>
</div>

</div>


<div id="page">
	
	<div id="content">
		
		<div class="post">
		<?php echo $this->layout()->content; ?>
		</div>
	</div>

	<div id="sidebar">
		<ul>
			<!-- 
			<li id="search">
				<h2><b class="text1">Search</b></h2>
				<form method="get" action="">
					<fieldset>
					<input type="text" id="s" name="s" value="" />
					<input type="submit" id="x" value="Search" />
					</fieldset>
				</form>
			</li>
			 -->
			
			<?php if(($active = $this->navigation()->findActive($this->navigation()->getContainer(), 0, 0)) && $subnavi = $this->navigation()->menu()->renderMenu($active['page'], array('minDepth' => 0, 'maxDepth' => 0, 'onlyActiveBranch' => false))): ?>
			<li>
			<h2><?php echo $active['page']->label; ?></h2>
			<?php echo $subnavi; ?>
			</li>
			<?php endif; ?>
			
			<li>
			<?php echo $this->layout()->sidebar_one; ?>
			</li>
			<li>
			<?php echo $this->layout()->sidebar_two; ?>
			</li>
			<li>
			<?php echo $this->layout()->sidebar_three; ?>
			</li>
		</ul>
	</div>

	<div style="clear: both;">&nbsp;</div>
</div>

<div id="footer">
	
	<?php echo $this->languageSwitcher(array('page' => $this->navigation()->findActive($this->navigation()->getContainer(), 0, 0)))?>
	
	
	<p id="legal">Copyright 2009 Mikko Forsström. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>
</div>

<?php echo $this->jQuery(); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->emerald()->googleAnalytics(); ?>

<script type="text/javascript">
Emerald.baseUrl = '<?php echo URL_BASE; ?>';
</script>

</body>

</html>
