<?php 
// @todo: this in init head maybe?
$this->headMeta()->appendHttpEquiv("Content-Type", "text/html; charset=UTF-8");
$this->headMeta()->appendName("Generator", "Emerald");
$this->jQuery()->enable()->uiEnable();
$this->jQuery()
	->addJavascriptFile("/lib/emerald.js");

$this->headLink()->appendStylesheet('/data/customer.css');

$this->headScript()->prependFile('/core/langlib/index/locale/' . Zend_Registry::get('Zend_Locale') . '/format/js');

$this->headMeta()->appendName("description", "Content management server built upon Zend Framework.");
$this->headMeta()->appendName("Author", "Mikko Forsström");
$this->headMeta()->appendName("Content-Language", "en");

$this->headTitle()->setSeparator(' - ');

?>

<?php echo $this->doctype('XHTML1_TRANSITIONAL'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="">

<head>
<?php echo $this->headMeta(); ?>
<?php print $this->headTitle(); ?>
<?php echo $this->headLink(); ?>
</head>

<body>
<div id="wrapper">

<div id="header">
	<div id="logo">
		<h1><a href="/">Emerald<sup></sup></a></h1>
		<h2>Content management built upon Zend Framework</h2>
	</div>
	<div id="menu">
	<?php echo $this->layout()->navi; ?>
	</div>
</div>

</div>


<div id="page">
	
	<div id="content">
		
		<div class="post">
		<?php echo $this->layout()->content; ?>
		</div>
	</div>

	<div id="sidebar">
		<ul>
			<!-- 
			<li id="search">
				<h2><b class="text1">Search</b></h2>
				<form method="get" action="">
					<fieldset>
					<input type="text" id="s" name="s" value="" />
					<input type="submit" id="x" value="Search" />
					</fieldset>
				</form>
			</li>
			 -->
			<li>
			<?php echo $this->layout()->sidebar_one; ?>
			</li>
			<li>
			<?php echo $this->layout()->sidebar_two; ?>
			</li>
			<li>
				<h2><b>Volutpat</b> Dolore</h2>
				<ul>
					<li><a href="#">Nec metus sed donec</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Velit semper nisi molestie</a></li>
					<li><a href="#">Eget tempor eget nonummy</a></li>
				</ul>
			</li>
		</ul>
	</div>

	<div style="clear: both;">&nbsp;</div>
</div>

<div id="footer">
	<p id="legal">Copyright 2009 Mikko Forsström. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>
</div>

<?php echo $this->jQuery(); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->googleAnalytics(); ?>

</body>

</html>
