<?php 
// @todo: this in init head maybe?
$this->jQuery()->enable();
$this->headLink()->appendStylesheet('/data/css/customer.css');
?>

<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<?php echo $this->headMeta(); ?>
<?php print $this->headTitle(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->jQuery(); ?>
<?php echo $this->headScript(); ?>
</head>

<body>
<div id="wrapper">
	<div id="header" class="container">
		<div id="logo">
			<h1><a href="http://drkobros.com/emerald-cms">Emerald CMS</a></h1>
			<p>
			A <a href="http://drkobros.com/">Dr. Kobros</a> &amp; <a href="http://foolabs.fi">Foolabs</a> project
			</p>
		</div>
		<div id="banner"><img src="/file/render/id/75" width="667" height="118" alt="" /></div>
	</div>
	
	<div id="menu" class="container">
	<?php echo $this->layout()->navi; ?>
	</div>
	
	<div id="top-bar" class="container">
		<div class="bar">
			<div class="text">Aliquam sit amet veroeros dolore sed tempus nullam</div>
			<div id="search">
				<form method="get" action="">
					<fieldset>
						<input type="text" name="query" value="" class="input-text" />
						<input type="submit" value="Search" class="input-submit" />
					</fieldset>
				</form>
			</div>
		</div>
	</div>
	
	<div id="page" class="container">
			<div id="content">
			<?php echo $this->layout()->content; ?>		
		</div>
		
		<div id="sidebar">
			<ul>
				<li>	
				<?php echo $this->layout()->sidebar_one; ?>
				</li>
				
				<li>	
				<?php echo $this->layout()->sidebar_two; ?>
				</li>
								
			</ul>
			
		</div>
		
		<div class="clearfix">&nbsp;</div>
		
		<div id="footer-bar" class="two-cols">
			<div class="col1">
				<h2>Aliquam sit amet veroeros</h2>
				<p>Faucibus non sit amet elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer placerat, dui sed posuere molestie, urna sapien porta purus, vel sodales ante erat sed arcu. Nunc semper, diam ut blandit elementum, ipsum purus vestibulum quam, sit amet auctor est ut risus. Maecenas sed dolore.</p>
			</div>
			<div class="col2">
				<ul>
					<li><a href="#">Faucibus non sit amet elit nulla</a></li>
					<li><a href="#">Consectetur adipiscing elit integer</a></li>
					<li><a href="#">Placerat dui sed posuere molestie</a></li>
					<li><a href="#">Urna sapien porta purus vel</a></li>
				</ul>
			</div>
			<div class="clearfix">&nbsp;</div>
		</div>
	
	
		
	</div>
</div>
<div id="footer" class="container">
	<p>(c) 2009 Sitename.com. Design by <a href="http://www.nodethirtythree.com/">nodethirtythree</a> + <a href="http://www.freecsstemplates.org/">Free CSS Templates</a></p>
</div>
</body>
</html>
