<?php
$this->headTitle()->append('File library');
$this->headScript()->appendFile(EMERALD_URL_BASE_LIB . '/lib/em-admin/filelib/index.js');

?>

<h1><?php echo $this->translate('File library'); ?></h1>

<div id="sidebar">

<h2><?php echo $this->translate('Folders'); ?></h2>


<ul>
<?php $depth = 0; $first = true; ?>

<?php foreach($this->iter as $folder): ?>
	
		
	<?php if($first): ?>
	<?php $first = false; ?>
	<?php else: ?>
	
	<?php if($this->iter->getDepth() > $depth) echo '<ul>'; ?>
	<?php if($this->iter->getDepth() < $depth) echo str_repeat('</li></ul>', $depth - $this->iter->getDepth()); ?>
	<?php if($this->iter->getDepth() == $depth) echo '</li>'; ?>
	
	<?php endif; ?>
		
	<li>						
	
	<?php if($this->emerald()->userIsAllowed($folder, 'read')): ?>
	
	<?php if($this->folder && $this->folder->getId() == $folder->getId()): ?>
	<strong><?php echo $folder->getName() == 'root' ? '/' : $folder->getName(); ?></strong>
	
	<?php if($this->folder->getParentId() != null): ?>
	<?php if($this->emerald()->userIsAllowed($folder, 'write')): ?>
	[<a class="emerald-confirm delete-folder" href="<?php echo $this->url(array('module' => 'em-admin', 'controller' => 'folder', 'action' => 'delete', 'id' => $folder->getId()), 'default', true); ?>"><?php echo $this->translate('Delete'); ?></a>]
	<?php endif;?>
	<?php endif; ?>

	<?php if($this->emerald()->userIsAllowed($folder, 'write')): ?>
	[<a href="<?php echo $this->url(array('module' => 'em-admin', 'controller' => 'folder', 'action' => 'edit', 'id' => $folder->getId()), 'default', true); ?>"><?php echo $this->translate('Edit'); ?></a>]
	<?php endif; ?>

	
	<?php else: ?>
	<a href="<?php echo EMERALD_URL_BASE; ?>/em-admin/filelib/index/id/<?php echo $folder->getId(); ?>">
	<?php echo $folder->getName() == 'root' ? '/' : $folder->getName(); ?>
	</a>
	<?php endif; ?>
	
	<?php endif; ?>
	
	<?php $depth = $this->iter->getDepth(); ?>
	
	<?php endforeach; ?>
	
	<?php if($depth) echo str_repeat('</li></ul>', $depth); ?>
	
</ul>

<?php if($this->folder): ?>

<?php if($this->emerald()->userIsAllowed($this->folder, 'write')): ?>

<h3><?php echo $this->translate('Create folder'); ?></h3>
<?php echo $this->folderForm; ?>
<?php endif; ?>

<?php endif; ?>

</div>

<div> 

<h2><?php echo $this->translate('Files'); ?></h2>

<?php if($this->files): ?>
<ul>
<?php foreach($this->files as $file): ?>
<li>
<a href="<?php echo $this->url(array('module' => 'em-filelib', 'controller' => 'file', 'action' => 'render', 'id' => $file->getId()), 'default', true); ?>"><?php echo $file->getName(); ?></a> (<?php echo $this->fl->file()->getType($file); ?>)

<?php if($this->emerald()->userIsAllowed($folder, 'write')): ?>
[<a class="emerald-confirm delete-file" href="<?php echo $this->url(array('module' => 'em-admin', 'controller' => 'file', 'action' => 'delete', 'id' => $file->getId()), 'default', true); ?>"><?php echo $this->translate('Delete'); ?></a>]
<?php endif; ?>
<br />
Versions:
<?php foreach($file->getFilelib()->getProfile($file->getProfile())->getFileVersions($file) as $fv): ?>
<a href="<?php echo $this->url(array('module' => 'em-filelib', 'controller' => 'file', 'action' => 'render', 'id' => $file->getId(), 'version' => $fv), 'default', true); ?>"><?php echo $fv; ?></a> 
<?php endforeach; ?>

</li>
<?php endforeach; ?>
</ul>

<?php if($this->emerald()->userIsAllowed($folder, 'write')): ?>

<h3><?php echo $this->translate('Upload file'); ?></h3>

<?php echo $this->form; ?>

<?php endif; ?>

<?php endif; ?>

</div>
