<?php
$this->headTitle()->append('File library');
$this->layout()->setLayout('emerald-plain');

// $this->emerald()->addTinyMCE();
$this->headScript()->appendFile(EMERALD_URL_BASE_LIB . '/lib/ext/tinymce/jscripts/tiny_mce/tiny_mce_popup.js');

$this->headScript()->appendFile(EMERALD_URL_BASE_LIB . '/lib/em-admin/filelib/select.js');


?>

<h1><?php echo $this->translate('File library'); ?></h1>

<div id="sidebar">

<h2><?php echo $this->translate('Folders'); ?></h2>


<ul>
<?php $depth = 0; $first = true; ?>

<?php foreach($this->iter as $folder): ?>

	<?php if($first): ?>
	<?php $first = false; ?>
	<?php else: ?>
	
	<?php if($this->iter->getDepth() > $depth) echo '<ul>'; ?>
	<?php if($this->iter->getDepth() < $depth) echo str_repeat('</li></ul>', $depth - $this->iter->getDepth()); ?>
	<?php if($this->iter->getDepth() == $depth) echo '</li>'; ?>
	
	<?php endif; ?>
		
	<li>						
	<?php if($this->folder && $this->folder->getId() == $folder->getId()): ?>
	<strong><?php echo $folder->getName() == 'root' ? '/' : $folder->getName(); ?></strong>
		
	<?php else: ?>
	<a href="<?php echo EMERALD_URL_BASE; ?>/em-admin/filelib/select/id/<?php echo $folder->getId(); ?>">
	<?php echo $folder->getName() == 'root' ? '/' : $folder->getName(); ?>
	</a>
	<?php endif; ?>
	
	<?php $depth = $this->iter->getDepth(); ?>
	
	<?php endforeach; ?>
	
	<?php if($depth) echo str_repeat('</li></ul>', $depth); ?>
	
</ul>


</div>

<div> 

<h2><?php echo $this->translate('Files'); ?></h2>

<?php if($this->files): ?>
<ul>
<?php foreach($this->files as $file): ?>
<li>
<a class="file" href="<?php echo $this->url(array('module' => 'em-filelib', 'controller' => 'file', 'action' => 'render', 'id' => $file->getId()), 'default', true); ?>"><?php echo $file->getName(); ?></a>
<br />
Versions:
<?php foreach($file->getProfileObject()->getFileVersions($file) as $fv): ?>
<a class="file" href="<?php echo $this->url(array('module' => 'em-filelib', 'controller' => 'file', 'action' => 'render', 'id' => $file->getId(), 'version' => $fv), 'default', true); ?>"><?php echo $fv; ?></a> 
<?php endforeach; ?>

</li>
<?php endforeach; ?>
</ul>

<?php endif; ?>

</div>
