<?php
$this->headScript()->appendFile(EMERALD_URL_BASE_LIB . "/lib/em-admin/sitemap/edit.js");
$this->headLink()->appendStylesheet(EMERALD_URL_BASE_LIB . "/lib/em-admin/sitemap/edit.css");
$this->headTitle('Edit sitemap')->headTitle('Sitemap');

$hasMenus = false;

?>

<h1><?php echo $this->translate('Edit sitemap'); ?></h1>

<div class="box">

<ul id="sitemap">
<?php $depth = 0; $first = true; ?>

<?php foreach($this->sitemap as $menu): ?>

	<?php if($first): ?>
	<?php $first = false; ?>
	<?php else: ?>
	
	<?php if($this->sitemap->getDepth() > $depth) echo '<ul>'; ?>
	<?php if($this->sitemap->getDepth() < $depth) echo str_repeat('</li></ul>', $depth - $this->sitemap->getDepth()); ?>
	<?php if($this->sitemap->getDepth() == $depth) echo '</li>'; ?>
	
	<?php endif; ?>
		
	<li class="node node-level-<?php echo $this->sitemap->getDepth(); ?>" id="page-<?php echo $menu->id; ?>">						
		
	<div class="node-row ui-widget ui-widget-content ui-corner-all">
		
	<?php if($menu->id): ?>

	<div class="label label-editable">	
	<span title="<?php echo $this->translate("Double click to edit"); ?>"><?php echo $menu->label; ?></span>
	</div>

	<?php else: ?>
	
	<div class="label">	
	<?php echo $menu->label; ?>
	</div>
			
	<?php endif; ?>

	<?php if($menu->id): ?>
	
	<?php $hasMenus = true; ?>
	
	<div class="features">
	<?php echo $this->formSelect("shard-{$menu->id}", $menu->shard_id, array('class' => 'shard'), $this->shardOpts); ?>
	<?php echo $this->formSelect("layout-{$menu->id}", $menu->layout, array('class' => 'layout'), $this->layoutOpts); ?>
	</div>	
	<?php endif; ?>
	
	<div class="actions">	

	<a href="<?php echo $this->url(array('module' => 'em-admin', 'controller' => 'page', 'action' => 'create', 'id' => $menu->id, 'locale' => $menu->locale), 'default', true); ?>">
	<?php echo $this->translate($menu->id ? 'Create subpage' : 'Create page'); ?>
	</a>

	<?php if($menu->id): ?>
	|
	<a href="<?php echo $this->url(array('module' => 'em-admin', 'controller' => 'page', 'action' => 'edit', 'id' => $menu->id), 'default', true); ?>">
	<?php echo $this->translate('Edit'); ?>
	</a>

	|

	<a class="delete emerald-confirm" href="<?php echo $this->url(array('module' => 'em-admin', 'controller' => 'page', 'action' => 'delete', 'id' => $menu->id, 'locale' => $menu->locale), 'default', true); ?>">
	<?php echo $this->translate('Delete'); ?>
	</a>
	<?php endif; ?>
			
	
			
	</div>
	
	<div class="clear"></div>
	
	</div>
	
	<?php $depth = $this->sitemap->getDepth(); ?>
	
	<?php endforeach; ?>
	
	<?php if($depth) echo str_repeat('</li></ul>', $depth); ?>
	
</ul>

<?php if(!$hasMenus): ?>
<?php
$localeModel = new EmCore_Model_Locale();
$locale = $localeModel->find($this->locale);
?>

<?php if($this->emerald()->userIsAllowed($locale, 'write')): ?>

<h2><?php echo $this->translate('Copy sitemap from another locale'); ?></h2>


<?php
$form = new EmAdmin_Form_SitemapCopy();
$form->setLocale($this->locale);
echo $form; ?>


<?php endif; ?>
<?php endif; ?>


</div>

