<h1><?php echo $this->translate('Users and Groups'); ?></h1>

<div>
	<ul class="iconVMenu noText">
		<li><?php echo $this->iconLarge("apps/personal", "Users", Array(), "Users","/admin/user/userList") ?></li>
		<li><?php echo $this->iconLarge("apps/kdmconfig", "Groups", Array(), "Groups","/admin/user/groupList") ?></li>
	</ul>
</div>
<br />
<nobr id="groupRowMenu" style="display: none">
<ul class="noText iconVMenu">
	<li class="rq_exactlyOne ac_editGroup"><?php echo $this->iconSmall("actions/configure", "Edit", Array(), $this->translate('Edit')) ?></li>
</ul>
</nobr>
<div id="ugContent">
	
	<table width="100%" cellspacing="0" class="entitityList">
		<thead>
			<tr class="columnHeadings">
				<th></th>
				<th><?php echo $this->translate('Name'); ?></th>
				<th></th> <?php /* commands */ ?>
			</tr>
			<tr class="flowControls">
				<th colspan="5">
					<div class="paging">
						<span class="title"><?php echo $this->translate('Page'); ?>:</span>
						<a href="" class="prevPage">&laquo;</a>
						<span class="currentPage">0</span> / <span class="totalPages">0</span>
						<a href="" class="nextPage">&raquo;</a>
					</div>
					<div class="selection">
						<span class="selectionCount">0</span> 
						<span class="title"><?php echo $this->translate('selected'); ?></span>,
						<span class="selectNone"><?php echo $this->translate('clear'); ?></span>
						::
						<ul class="dynamicMenu iconVMenu" id="topMenukko">
							<li class="ac_addGroup"><?php echo $this->iconSmall("actions/edit_add", "Add Group", Array(), $this->translate('Add Group'),"/admin/user/viewNewGroup") ?></li>
							<li class="rq_exactlyOne ac_editGroup"><?php echo $this->iconSmall("actions/configure", "Edit", Array(), $this->translate('Edit')) ?></li>
							<li class="rq_atLeastOne rq_confirm ac_deleteGroup"><?php echo $this->iconSmall("actions/editdelete", "Delete", Array(), $this->translate('Delete')) ?></li>
						</ul>
						<span id="activeCommand"></span>
					</div>
				</th>
			</tr>
		</thead>
		<tbody></tbody>
	</table>
</div>
<div class="clearer"></div>