<?php
$this->headTitle()->append('Users & groups');
$this->headScript()->appendFile(EMERALD_URL_BASE_LIB . "/lib/admin/user/index.js");
?>

<h1><?php echo $this->translate('Users & groups'); ?></h1>

<div id="tabs">

<ul>
	<li><a href="#users"><?php echo $this->translate('Users'); ?></a></li>
	<li><a href="#groups"><?php echo $this->translate('Groups'); ?></a></li>
</ul>

<div id="users">

<p>
<a href="<?php echo $this->url(array('action' => 'create')); ?>"><?php echo $this->translate('Create user'); ?></a>
</p>

<ul>
<?php foreach($this->users as $user): ?>
<li>
<a href="<?php echo $this->url(array('action' => 'edit', 'id' => $user->id)); ?>"><?php echo $user->email; ?></a><br />
<?php echo $this->translate("Groups "); ?>: 
<?php foreach($user->getGroups() as $group): ?>
<?php echo $group->name; ?>, 
<?php endforeach; ?>
<br />
<a class="user-delete emerald-confirm" href="<?php echo $this->url(array('action' => 'delete', 'id' => $user->id)); ?>"><?php echo $this->translate('Delete'); ?></a>
</li>
<?php endforeach; ?>
</ul>


</div>

<div id="groups">

<p>
<a href="<?php echo $this->url(array('controller' => 'group', 'action' => 'create')); ?>"><?php echo $this->translate('Create group'); ?></a>
</p>

<ul>
<?php foreach($this->groups as $group): ?>
<li>
<a href="<?php echo $this->url(array('controller' => 'group', 'action' => 'edit', 'id' => $group->id)); ?>"><?php echo $group->name; ?></a><br />
<?php echo $this->translate("Users "); ?>: 
<?php foreach($group->getUsers() as $user): ?>
<?php echo $user->email; ?>, 
<?php endforeach; ?>
<br />
<a class="group-delete emerald-confirm" href="<?php echo $this->url(array('controller' => 'group', 'action' => 'delete', 'id' => $group->id)); ?>"><?php echo $this->translate('Delete'); ?></a>
</li>
<?php endforeach; ?>
</ul>


</div>

</div>