<h1><?php echo $this->translate('Users and Groups'); ?></h1>

<nobr id="userRowMenu" style="display: none">
<ul class="noText iconVMenu">
	<li class="rq_exactlyOne ac_editUser"><?php echo $this->iconSmall("actions/configure", "Edit", Array(), $this->translate('Edit')) ?></li>
</ul>
</nobr>
<nobr id="groupRowMenu" style="display: none">
<ul class="noText iconVMenu">
	<li class="rq_exactlyOne ac_editGroup"><?php echo $this->iconSmall("actions/configure", "Edit", Array(), $this->translate('Edit')) ?></li>
</ul>
</nobr>


<div id="container-1">
	<ul>
		<li class="ui-tabs-nav-item"><a href="#userList"><span><?php echo $this->translate('Users'); ?></span></a></li>
		<li class="ui-tabs-nav-item"><a href="#groupList"><span><?php echo $this->translate('Groups'); ?></span></a></li>
		<!-- 
		<li><?php echo $this->iconLarge("apps/personal", "Users", Array(), "Users","/admin/user/userList") ?></li>
		<li><?php echo $this->iconLarge("apps/kdmconfig", "Groups", Array(), "Groups","/admin/user/groupList") ?></li>
		 -->
	</ul>
	<div id="userList">
		<table width="100%" cellspacing="0" class="entitityList">
			<thead>
				<tr class="columnHeadings">
					<th>&nbsp;</th>
					<th><?php echo $this->translate('Email'); ?></th>
					<th>&nbsp;</th><?php /* commands */ ?>
					<th><?php echo $this->translate('First Name'); ?></th>
					<th><?php echo $this->translate('Last Name'); ?></th>
				</tr>
				<tr class="flowControls">
					<th colspan="5">
						<div class="paging">
							<span class="title"><?php echo $this->translate('Page'); ?>:</span>
							<a href="" class="prevPage">&laquo;</a>
							<span class="currentPage">0</span> / <span class="totalPages">0</span>
							<a href="" class="nextPage">&raquo;</a>
						</div>
						<div class="selection">
							<span class="selectionCount">0</span> 
							<span class="title"><?php echo $this->translate('selected'); ?></span>,
							<span class="selectNone"><?php echo $this->translate('clear'); ?></span>
							::
							<ul class="dynamicMenu iconVMenu" id="topMenukko">
								<li class="ac_addUser"><?php echo $this->iconSmall("actions/edit_add", "Add user", Array(), $this->translate('Add user'),"/admin/user/viewNewUser") ?></li>
								<li class="rq_atLeastOne rq_confirm ac_deleteUser"><?php echo $this->iconSmall("actions/editdelete", "Delete", Array(), $this->translate('Delete')) ?></li>
							</ul>
							<span id="activeUserCommand"></span>
						</div>
					</th>
				</tr>
			</thead>
			<tbody></tbody>
		</table>
	</div>
	<div id="groupList">
		
		<table width="100%" cellspacing="0" class="entitityList">
			<thead>
				<tr class="columnHeadings">
					<th></th>
					<th><?php echo $this->translate('Name'); ?></th>
					<th></th> <?php /* commands */ ?>
				</tr>
				<tr class="flowControls">
					<th colspan="5">
						<div class="paging">
							<span class="title"><?php echo $this->translate('Page'); ?>:</span>
							<a href="" class="prevPage">&laquo;</a>
							<span class="currentPage">0</span> / <span class="totalPages">0</span>
							<a href="" class="nextPage">&raquo;</a>
						</div>
						<div class="selection">
							<span class="selectionCount">0</span> 
							<span class="title"><?php echo $this->translate('selected'); ?></span>,
							<span class="selectNone"><?php echo $this->translate('clear'); ?></span>
							::
							<ul class="dynamicMenu iconVMenu" id="topMenukko">
								<li class="ac_addGroup"><?php echo $this->iconSmall("actions/edit_add", "Add Group", Array(), $this->translate('Add Group'),"/admin/user/viewNewGroup") ?></li>
								<li class="rq_atLeastOne rq_confirm ac_deleteGroup"><?php echo $this->iconSmall("actions/editdelete", "Delete", Array(), $this->translate('Delete')) ?></li>
							</ul>
							<span id="activeGroupCommand"></span>
						</div>
					</th>
				</tr>
			</thead>
			<tbody></tbody>
		</table>
	</div>
</div>
<?php /** container -1 */ ?>