<?php 
$this->headTitle()->append('Dashboard');
$this->headScript()->appendFile("/lib/admin/index/index.js");
?>

<h1><?php echo $this->translate('Dashboard'); ?></h1>

<p><?php echo $this->translate('Welcome to Emerald.'); ?></p>

<h2><?php echo $this->translate('Developer tools'); ?></h2>

<ul>
<li><a id="clear-cache" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'cache', 'action' => 'clear'), 'default', true); ?>"><?php echo $this->translate('Clear caches'); ?></a></li>
</ul>
