<h1><?php echo $this->translate('admin/dashboard/title'); ?></h1>

<p><strong><?php echo $this->translate('emerald/server/version'); ?>:</strong> <?php print Emerald_Server::getInstance()->getVersion(); ?></p>

<p><?php echo $this->translate('admin/dashboard/explanation'); ?></p>


<?php if($this->feed): ?>
<h2><?php echo $this->translate('admin/dashboard/emerald_news'); ?></h2>
<div id="emeraldNews">
<?php foreach($this->feed as $item): ?>
<div class="emeraldNewsItem">
<h3><?php print $item->title; ?></h3>
<p><a href="<?php print $item->link; ?>"><?php print $item->description; ?></a></p>
</div>
<?php endforeach; ?>
</div>
<?php endif; ?>