<div id="newsSplitter">

	<div class="newsItemView">
	
	<?php $date = new Zend_Date($this->item->valid_start, Zend_Date::ISO_8601); ?>
	
	<div class="newsItem <?php if(!$this->item->isValid()): ?> newsItemInvalid <?php endif; ?>">
	
		<h2>
		<?php // echo $date->get(Zend_Date::DATE_MEDIUM, $this->page->getLocale()) ?>
		<?php // echo $date->get(Zend_Date::TIME_SHORT, $this->page->getLocale()); ?> <?php echo $this->item->title; ?>
		</h2>
		
		<div class="newsItemDescription">
		<?php echo $this->item->description; ?>
		</div>
		
		<div class="newsItemArticle">
		<?php echo $this->item->article; ?>
		</div>
		
		
	</div>
	
	<?php if($this->writable): ?>
		<div class="adminControl adminControlLight">
		<a id="newsitem_edit" class="popup popup_large popup_resizable popup_scrollbars" href="/admin/newsitem/edit/id/<?php echo $this->item->id; ?>"><?php echo $this->translate('shard/news/item/edit_item'); ?></a>
	 | <a class="confirmable" href="/admin/newsitem/delete/id/<?php echo $this->item->id; ?>"><?php echo $this->translate('common/delete'); ?></a>
		</div>
	<?php endif; ?>	
	
	</div>

	<div class="headlines">
			
	<?php echo $this->shard($this->page, 'Htmlcontent', array('a' => 'index', 'block_id' => 567)); ?>
			
	<?php echo $this->shard($this->page, 'News', array('a' => 'headlines', 'headlines' => 10)); ?>	
	</div>
	




</div>
