<?php
$this->headTitle("Edit html content")->headTitle($this->page->title);

$this->headScript()->appendFile(URL_BASE . '/lib/tinymce/jscripts/tiny_mce/jquery.tinymce.js');
$this->headScript()->appendFile(URL_BASE . "/lib/core/html-content/edit.js");

$this->layout()->setLayout("plain");

?>

<h2><?php echo $this->translate('Edit html content'); ?></h2>

<?php echo $this->form; ?>

<script type="text/javascript">
var beautifurl = Emerald.baseUrl + '/' + '<?php echo $this->page->beautifurl; ?>';

</script>

