<?php echo $this->htmlcontent->content; ?>

<?php if($this->writable): ?>

<?php
$model = new Core_Model_Page();
$siblings = $model->findSiblings($this->page);
?>

<div class="emerald-controls emerald-controls-html-content" id="emerald-controls-html-content-<?php echo $this->htmlcontent->page_id; ?>-<?php echo $this->htmlcontent->block_id; ?>">
<a rel="emerald-htmlcontent-edit" class="emerald-popup popup-large popup-resizable popup-scrollbars" 
href="<?php echo $this->url(array('module' => 'core', 'controller' => 'html-content', 'action' => 'edit', 'page_id' => $this->htmlcontent->page_id, 'block_id' => $this->htmlcontent->block_id), 'default', true); ?>">
<?php echo $this->translate('Edit'); ?>
</a>

<div class="emerald-htmlcontent-locales">

<p><?php echo $this->translate('This page in different locales'); ?></p>
<ul>
<?php foreach($siblings as $sibling): ?>
<li><a href="<?php echo EMERALD_URL_BASE; ?>/<?php echo $sibling->beautifurl; ?>"><?php echo $sibling->title; ?></a></li>
<?php endforeach; ?>
</ul>
</div>

</div>
<?php endif; ?>