<?php 
$this->headTitle()->append('Forms');
$this->headScript()->appendFile("/lib/admin/form/index.js");
?>

<div id="forms">

<h1><?php echo $this->translate('Forms'); ?></h1>


<h2><?php echo $this->translate('Create a new form'); ?></h2>

<?php echo $this->form; ?>

<h2><?php echo $this->translate('Existing forms'); ?></h2>


<table class="entitityList">
<thead>
	<tr>
		<th><?php echo $this->translate('Name'); ?></th>
		<th><?php echo $this->translate('Description'); ?></th>
		<th><?php echo $this->translate('Actions'); ?></th>
	</tr>
</thead>
<tbody>
<?php foreach($this->forms as $form): ?>
<tr>
	<td><?php echo $form->name; ?></td>
	<td><?php echo $form->description; ?></td>
	<td>
		<a href="<?php echo $this->url(array('action' => 'edit', 'id' => $form->id)); ?>"><?php echo $this->translate('Edit'); ?></a> |
		<a class="emerald-confirm form-delete" href="<?php echo $this->url(array('action' => 'delete', 'id' => $form->id)); ?>"><?php echo $this->translate('Delete'); ?></a>
	</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>

</div>