<div id="formController">

<h1><?php echo $this->translate('admin/form/title'); ?></h1>


<h2><?php echo $this->translate('admin/form/title/create_new'); ?></h2>

<form method="post" action="/admin/form/create">

<label for="name"><?php echo $this->translate('admin/form/label/name'); ?></label>
<input id="name" name="name" class="w13" type="text" />

<label for="description"><?php echo $this->translate('admin/form/label/description'); ?></label>
<textarea id="description" name="description" class="w33"></textarea>


<p>
<button type="submit" class="submit niceButton"><?php echo $this->translate('common/create'); ?></button>
</p>

</form>

<h2><?php echo $this->translate('admin/form/title/existing_forms'); ?></h2>


<table class="entitityList">
<thead>
	<tr>
		<th><?php echo $this->translate('admin/form/label/name'); ?></th>
		<th><?php echo $this->translate('admin/form/label/description'); ?></th>
		<th><?php echo $this->translate('common/actions'); ?></th>
	</tr>
</thead>
<tbody>
<?php foreach($this->forms as $form): ?>
<tr>
	<td><?php echo $form->name; ?></td>
	<td><?php echo $form->description; ?></td>
	<td>
		<a href="/admin/form/edit/id/<?php echo $form->id; ?>"><?php echo $this->translate('common/edit'); ?></a> |
		<a class="confirmable" href="/admin/form/delete/id/<?php echo $form->id; ?>"><?php echo $this->translate('common/delete'); ?></a>
	</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>

</div>