<h1><?php echo $this->translate('News :: Edit'); ?></h1>

<form id="edit" method="post" action="/admin/newsitem/update/id/<?php echo $this->item->id; ?>">

<label for="title"><?php echo $this->translate('Title'); ?></label>
<?php echo $this->formText('title', $this->item->title, array('class' => 'w100')); ?>

<label for="description"><?php echo $this->translate('Short description'); ?></label>
<?php echo $this->formTextarea('description', $this->item->description, array('rows' => 3, 'class' => 'w100 mceEditablex')); ?>

<label for="article"><?php echo $this->translate('Content'); ?></label>
<?php echo $this->formTextarea('article', $this->item->article, array('rows' => 15, 'class' => 'w100 mceEditor')); ?>

<label for="valid_start"><?php echo $this->translate('Publish'); ?></label>
<?php echo $this->formSelectDate('valid_start', ($now = new Zend_Date($this->item->valid_start, Zend_Date::ISO_8601)), new Zend_Date('2007-01-01', 'fi_FI'), new Zend_Date('2015-12-31', 'fi_FI'), array()); ?>

<label for="valid_end"><?php echo $this->translate('Expire'); ?></label>
<?php echo $this->formSelectDate('valid_end', new Zend_Date($this->item->valid_end, Zend_Date::ISO_8601), new Zend_Date('2007-01-01', 'fi_FI'), new Zend_Date('2015-12-31', 'fi_FI'), array()); ?>

<p>
<?php echo $this->formHidden('status', 0); ?>
<?php echo $this->formCheckbox('status', 1, array('checked' => $this->item->status)); ?> <?php echo $this->translate('Active'); ?>
</p>

<p>
<?php echo $this->formButton('submiter', $this->translate('Submit'), array('type' => 'submit')); ?>
</p>

</form>