<h1>{l:shard/news/item/edit}</h1>

<form id="edit" method="post" action="/admin/newsitem/update/id/<?php echo $this->item->id; ?>">

<label for="title">{l:shard/news/item/title}</label>
<?php echo $this->formText('title', $this->item->title, array('class' => 'w100')); ?>

<label for="description">{l:shard/news/item/description}</label>
<?php echo $this->formTextarea('description', $this->item->description, array('rows' => 3, 'class' => 'w100 mceEditablex')); ?>

<label for="article">{l:shard/news/item/article}</label>
<?php echo $this->formTextarea('article', $this->item->article, array('rows' => 15, 'class' => 'w100 mceEditor')); ?>

<label for="valid_start">{l:shard/news/item/valid_start}</label>
<?php echo $this->formSelectDate('valid_start', ($now = new Zend_Date($this->item->valid_start, Zend_Date::ISO_8601)), new Zend_Date('2007-01-01', 'fi_FI'), new Zend_Date('2015-12-31', 'fi_FI'), array()); ?>

<label for="valid_end">{l:shard/news/item/valid_end}</label>
<?php echo $this->formSelectDate('valid_end', new Zend_Date($this->item->valid_end, Zend_Date::ISO_8601), new Zend_Date('2007-01-01', 'fi_FI'), new Zend_Date('2015-12-31', 'fi_FI'), array()); ?>

<p>
<?php echo $this->formHidden('status', 0); ?>
<?php echo $this->formCheckbox('status', 1, array('checked' => $this->item->status)); ?> {l:shard/news/item/status_active}
</p>

<p>
<?php echo $this->formButton('submiter', '{l:common/submit}', array('type' => 'submit')); ?>
</p>

</form>