<h1><?php echo $this->translate('File uploaded'); ?></h1>

<div class="box">

<p>
<?php if($this->success): ?>
<?php echo $this->translate('File upload ok'); ?>
<?php else: ?>
<?php echo $this->translate('File upload failed'); ?>
<?php endif;?>
</p>

<p>
<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'filelib', 'action' => 'index', 'id' => $this->folder_id), 'default', true); ?>">
<?php echo $this->translate('Back'); ?>
</a>
</p>


</div>