<h1><span id="data_page_title"></span> {l:common/properties}</h1>
<form action="" name="pageproperties" id="pageproperties" class="paddedContent" method="post">
<table class="horizontalData">
	<tr>
		<th><label for="title">{l:page/title}</label></th>
		<td><input name="title" id="title" value="" /></td>
	</tr>
	<tr>
		<th><label for="shard_id">{l:page/shard}</label></th>
		<td>
		<select name="shard_id" id="shard_id" value="">
			<?php foreach($this->shards as $srv): ?>
				<option value="<?php echo $srv->id ?>">{l:common/shardnames/<?php echo $srv->id ?>}</option>
			<?php endforeach; ?>
		</select>
		</td>
	</tr>
	<tr>
		<th><label for="template">{l:page/template}</label></th>
		<td>
		<select name="template" id="template" value="">
			<?php foreach($this->templates as $tpl): ?>
				<option value="<?php echo $tpl ?>"><?php echo $tpl ?></option>
			<?php endforeach; ?>
		</select>
		</td>
	</tr>
	<tr>
		<th><label for="innertemplate">{l:page/innertemplate}</label></th>
		<td>
		<select name="innertemplate" id="innertemplate" value="">
			<?php foreach($this->innertemplates as $tpl): ?>
				<option value="<?php echo $tpl ?>"><?php echo $tpl ?></option>
			<?php endforeach; ?>
		</select>
		</td>
	</tr>

	<tr>
		<th><label for="visibility">{l:page/visibility}</label></th>
		<td>
		<select name="visibility" id="visibility">
			<option value="1">{l:page/visibility/visible}</option>			
			<option value="0">{l:page/visibility/hidden}</option>
		</select>
		</td>
	</tr>

	<?php if(!$this->id): ?>
	<tr>
		<th><label for="page_count">{l:page/page_count}</label></th>
		<td>
		<select name="page_count" id="page_count">
			<?php for($i = 1 ; $i < 11;  $i++): ?>
				<option value="<?php echo $i ?>"><?php echo $i ?></option>
			<?php endfor; ?>
		</select>
		</td>
	</tr>
	<?php endif; ?>
</table>

<fieldset>
	<legend>{l:page/permissions}</legend>
	<table>
		<thead>
			<tr>
				<th>{l:page/groupname}</th>
				<?php foreach($this->permissions as $permission): ?>
				<th><?php echo $permission ?></th>
				<?php endforeach; ?>
			</tr>	
		</thead>
		<tbody>
		<?php foreach($this->groups as $group): ?>
		<tr>
			<td><?php echo $group->name ?></td>
			<?php foreach($this->permissions as $permissionId => $permission): ?>
				<td>

					<?php
					if(!$this->page) {
						if($group->id == 1 && $permissionId == 4 || $group->id == 2)
							$forceCheck = true;
						else {
							$forceCheck = false;
						}
					} else {
						$forceCheck = false;
					}
					?>

					<input	type="checkbox" 
							name="permission[<?php echo $group->id ?>][]"
							<?php if($forceCheck || $this->page && $this->acl->isAllowed($group, $this->page, $permission)) echo "checked=\"checked\"" ?>
							value="<?php echo $permissionId ?>"
					/>
				</td>
			<?php endforeach; ?>
			
		</tr>
		<?php endforeach; ?>
		</tbody>	
	</table>
</fieldset>
<br />

<input name="id" value="<?php echo $this->id ?>" type="hidden" />
<input name="locale" value="<?php echo $this->escape($this->localeName) ?>" type="hidden" />
<input name="parent_id" value="<?php echo $this->parentId ?>" type="hidden" />
<button type="submit" class="submit niceButton">{l:page/submit}</button>
</form>