<?php
$this->headScript()->appendFile("/lib/admin/sitemap/index.js");
$this->headLink()->appendStylesheet("/lib/admin/sitemap/index.css");
$this->headTitle()->append('Sitemap');
?>

<h1><?php echo $this->translate('Sitemap'); ?></h1>

<ul id="sitemap">
<?php $depth = 0; $first = true; ?>

<?php foreach($this->sitemap as $menu): ?>

	<?php if($first): ?>
	<?php $first = false; ?>
	<?php else: ?>
	
	<?php if($this->sitemap->getDepth() > $depth) echo '<ul>'; ?>
	<?php if($this->sitemap->getDepth() < $depth) echo str_repeat('</li></ul>', $depth - $this->sitemap->getDepth()); ?>
	<?php if($this->sitemap->getDepth() == $depth) echo '</li>'; ?>
	
	<?php endif; ?>
		
	<li class="node node-level-<?php echo $this->sitemap->getDepth(); ?>" id="page-<?php echo $menu->id; ?>">						
		
	<?php if($menu->id): ?>

	<div class="label label-editable">	
	<?php echo $menu->label; ?>
	</div>

	<?php else: ?>
	
	<div class="label">	
	<?php echo $menu->label; ?>
	</div>
			
	<?php endif; ?>
	
	<div class="actions">	
	
	<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'page', 'action' => 'edit', 'id' => $menu->id), 'default', true); ?>">
	<?php echo $this->translate('Edit'); ?>
	</a>

	<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'page', 'action' => 'create', 'id' => $menu->id, 'locale' => $menu->locale), 'default', true); ?>">
	<?php echo $this->translate('Create page'); ?>
	</a>

	<a class="delete" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'page', 'action' => 'delete', 'id' => $menu->id, 'locale' => $menu->locale), 'default', true); ?>">
	<?php echo $this->translate('Delete'); ?>
	</a>
			
	
			
	</div>
	
	<div class="clear"></div>
			
	
	<?php $depth = $this->sitemap->getDepth(); ?>
	
	<?php endforeach; ?>
	
	<?php if($depth) echo str_repeat('</li></ul>', $depth); ?>
	
</ul>



