<?php
$this->headScript()->appendFile("/lib/admin/sitemap/index.js");
$this->headTitle()->append('Sitemap');
?>

<h1><?php echo $this->translate('Sitemap'); ?></h1>

<ul>
<?php $depth = 0; $first = true; ?>

<?php foreach($this->sitemap as $menu): ?>

	<?php if($first): ?>
	<?php $first = false; ?>
	<?php else: ?>
	
	<?php if($this->sitemap->getDepth() > $depth) echo '<ul>'; ?>
	<?php if($this->sitemap->getDepth() < $depth) echo str_repeat('</li></ul>', $depth - $this->sitemap->getDepth()); ?>
	<?php if($this->sitemap->getDepth() == $depth) echo '</li>'; ?>
	
	<?php endif; ?>
		
	<li>						
	<?php echo $menu->label; ?>
	<br />
	<?php if($menu->id): ?>
	<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'page', 'action' => 'edit', 'id' => $menu->id), 'default', true); ?>">
	<?php echo $this->translate('Edit page'); ?>
	</a>
	<?php endif; ?>
	<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'page', 'action' => 'create', 'id' => $menu->id, 'locale' => $menu->locale), 'default', true); ?>">
	<?php echo $this->translate('Create page'); ?>
	</a>

	<a class="delete" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'page', 'action' => 'delete', 'id' => $menu->id, 'locale' => $menu->locale), 'default', true); ?>">
	<?php echo $this->translate('Delete'); ?>
	</a>
	
	
	<?php $depth = $this->sitemap->getDepth(); ?>
	
	<?php endforeach; ?>
	
	<?php if($depth) echo str_repeat('</li></ul>', $depth); ?>
	
</ul>


