<h1><?php echo $this->translate('Reorder titles'); ?></h1>
<p><?php echo $this->translate('Drag &amp; Drop pages to new position'); ?></p>
<div id="sortTree">
<?php echo $this->pageList ?>
</div>
<button id="sortCancel" class="cancel niceButton"><?php echo $this->translate('Cancel'); ?></button>
<button id="sortCommit" class="submit niceButton"><?php echo $this->translate('Submit'); ?></button>
<style>
#sortTree
{
	margin: 0em 1em;
	padding: 0em 0.5em 0em 5em;
}
ol
{
	
	background-color: #fff;
	dlist-style-type: none;
	padding: 5px;
	color: #333;
	font-weight: bold;
	dborder: 1px solid #555;
	
}
ol ol {padding: 5px 0 5px 20px;}
li
{
	padding-left: 20px;
	background-image: url('/lib/gfx/nuvola/16x16/mimetypes/html.png');
	background-repeat: no-repeat;
	dbackground-position: 0.1em 1em ;
}
li.homePage
{
	background-image: url('/lib/gfx/nuvola/16x16/actions/gohome.png');
}
</style>
<script type="text/javascript">
$j(document).ready(function() {
	Sortable.create("sortList", {tree:true,scroll:window, dropOnEmpty:true,treeTag:"ol"});
	
	$('sortCancel').observe("click",function()
	{
		if(Emerald.confirm("common/cancel_edit"))
		{
			window.close();
		}
	});
	$('sortCommit').observe("click",function()
	{
		var poststring = Sortable.serialize('sortList');
		console.debug(poststring);
		$j.ajax({
			url: "/admin/sitemap/updateOrder/locale/<?php echo $this->locale ?>",
			data: poststring,
			type: 'post',
			dataType: 'json',
			success: (function(data)
			{
				if(data.type == 4) {
					Emerald.message("The requested operation could not be completed, please try again.");
				} else {
				
					if(Emerald.confirm("common/operation_success_confirm_close"))
					{
						window.close();
					}
				}
				window.opener.document.location.reload();
				
			}).bind(this)
		});
	});
});
</script>