<?php 
// @todo: this in init head maybe?

$this->emerald()->addEverything();

$this->jQuery()
	->addJavascriptFile(EMERALD_URL_BASE_DATA . '/data/jquery.hashchange.js')
	->addJavascriptFile(EMERALD_URL_BASE_DATA . '/data/jquery.marquee.js')
	->addJavascriptFile(EMERALD_URL_BASE_DATA . '/data/jquery.cookie.js');

$this->headLink(array('rel' => 'icon', 'href' => EMERALD_URL_BASE_DATA . '/data/images/manatee-favicon.png'));

$this->headScript()->appendFile(EMERALD_URL_BASE_DATA . "/data/lamantiini.js");

$this->headMeta()->appendName("description", "Mikko Forsströmin pieni ja sievä ovimatto: linkit projekteihin, aktiivisiin ja arkistoituihin.");
$this->headMeta()->appendName("Author", "Mikko Forsström");
$this->headMeta()->appendName("Content-Language", "fi");
$this->headMeta()->appendName("geo.region", "FI-ES");
$this->headMeta()->appendName("geo.placename", "Vantaa");
$this->headMeta()->appendName("geo.position", "60.267045;24.857329");
$this->headMeta()->appendName("ICBM", "60.267045, 24.857329");


?>

<?php echo $this->doctype('XHTML1_TRANSITIONAL'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="">

<head>
<?php echo $this->headMeta()->setIndent(4); ?>
<?php echo $this->headTitle()->setIndent(4); ?>
<?php echo $this->headLink()->setIndent(4); ?>
</head>

<body>

<canvas id="luss"></canvas>

<div id="manatee-menu">
<?php echo $this->translate('Manatee Menu')?>&trade;

<ul>
	<li>Mode: <a rel="noajax" id="manatee-mode" href="#">undefined</a></li>
</div>

	
<div style="position:absolute;top:0;right:0;margin:0;padding:0"><a href="http://www.eroakirkosta.fi" target="_top"><img src="http://www.eroakirkosta.fi/static/images/enmaksa.gif" alt="eroakirkosta.fi" border="0" title="En maksa kirkollisveroa!" /></a></div>
	
<div id="ie-container">
<div id="outer-container">
	<div id="inner-container">
		
		<div id="logo">
		
		<img id="logo-lamantee" src="<?php echo EMERALD_URL_BASE_DATA; ?>/data/images/manatee.png" />
				
		<h1>Lamantiini 2k10</h1>
				
		</div>
		
		
				
		<div id="shadow-container">
				
		<div id="container-container">
		
		<div id="main-menu">	
		<div class="menu">
		<?php echo $this->navigation()->menu()->renderMenu(null, array('minDepth' => 0, 'maxDepth' => 1, 'onlyActiveBranch' => false)); ?>
		</div>
		<div class="clearer"></div>	
		</div>

		
		<div id="content-container">
		
		<?php echo $this->layout()->content; ?>
		</div>		
			
		</div>
		</div>
		
		<div id="footer">
		<a href="http://emerald.fi">powered by Emerald</a> / PostgreSQL, Zend Framework and jQuery
		
		<?php if($this->emerald()->userIsAllowed($this->emerald()->findActivity('Administration', 'Expose admin panel'))): ?>
		| <a rel="emerald-admin-panel" title="<?php echo $this->translate('Open admin panel'); ?>" class="emerald-popup popup-huge popup-scrollbars" href="<?php echo $this->url(array('module' => 'admin'), 'default', true); ?>"><?php echo $this->translate('Admin panel'); ?></a>		
		<?php endif; ?>
		
		</div>
		
	
		
		
	</div>
	
</div>
</div>

<?php echo $this->jQuery(); ?>
<?php echo $this->headScript(); ?>
<?php echo $this->emerald()->googleAnalytics(); ?>

<script type="text/javascript">
Emerald.URL_BASE = '<?php echo EMERALD_URL_BASE; ?>';
Emerald.URL_BASE_LIB = '<?php echo EMERALD_URL_BASE_LIB; ?>';
Emerald.URL_BASE_DATA = '<?php echo EMERALD_URL_BASE_DATA; ?>';
</script>


</body>

</html>
