<label class="formContentLabel <?php echo ($this->field->mandatory) ? 'required' : 'optional' ; ?>" for="form_<?php echo $this->form->id; ?>_field_<?php echo $this->field->id; ?>"><?php echo $this->field->title; ?></label>
<?php echo $this->formTextarea("form_{$this->form->id}_field_{$this->field->id}", null, array(
	'class' => "field_type_{$this->field->type}",
	'cols' => 40,
	'rows' => 5,
)); ?>