<h1><?php echo $this->translate('About Emerald'); ?></h1>

<div class="box">

<p>
<strong><?php echo $this->translate('Emerald version'); ?>:</strong> <?php print Emerald_Version::VERSION; ?><br />
<strong><?php echo $this->translate('Zend Framework version'); ?>:</strong> <?php print Zend_Version::VERSION; ?><br />
<strong><?php echo $this->translate('PHP version'); ?>:</strong> <?php print PHP_VERSION; ?>
</p>

<h2>Development lead</h2>

<ul>
<li>Mikko "Pekkis" Forsström</li>
</ul>

<h2>Contributors</h2>

<ul>
<li>Mikko Hirvonen</li>
<li>Petri Mahanen</li>
<li>Henri Vesala</li>
<li>Jorma Tuomainen</li>
<li>Petri Heinonen</li>
<li>Mikko Hämäläinen</li>
</ul>

<h2>Corporate sugar daddies</h2>

<ul>
<li>Soprano Brain Alliance Ltd.</li>
<li>Foolabs Ltd.</li>
</ul>

<h2>Special thanks</h2>

<ul>
<li>Dr. Kobros Foundation</li>
</ul>


</div>