<?php $this->layout()->disableLayout(); ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<link rel="stylesheet" href="/lib/css/admin/emerald_popup.css" />
	</head>

	
	<body id="popup">
		
		<div id="pageContainer">
	
				<h1>emerald error</h1>
				<p><?php echo $this->message; ?></p>
		</div>
	
	</body>
	
	
</html>