<?php
$this->headTitle('Edit form')->headTitle('Forms');
$this->headScript()->appendFile(EMERALD_URL_BASE_LIB . '/lib/em-admin/form/edit.js');
$this->headLink()->appendStylesheet(EMERALD_URL_BASE_LIB . '/lib/em-admin/form/edit.css');
?>



<h1><?php echo $this->translate('Edit form'); ?></h1>

<div class="box">

<?php echo $this->fieldCreateForm; ?>

<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<th class="type"><?php echo $this->translate('Field type'); ?></th>
<th class="ftitle"><?php echo $this->translate('Title'); ?></th>
<th class="mandatory"><?php echo $this->translate('Required'); ?></th>
<th class="options"><?php echo $this->translate('Options'); ?></th>
<th class="actions"><?php echo $this->translate('Actions'); ?></th>
</table> 


<form id="field-edit" method="post" action="<?php echo $this->url(array('module' => 'em-admin', 'controller' => 'form', 'action' => 'save'), 'default', true); ?>">

<input type="hidden" name="form_id" value="<?php echo $this->form->id; ?>" />

<div id="form-sort">
<?php foreach($this->form->getFields() as $key => $field): ?>

<div class="form-sortable ui-widget ui-widget-content ui-corner-all ui-widget-state-default">

<input type="hidden" name="id[<?php echo $key; ?>]" value="<?php echo $field->id; ?>" />

<table width="100%" border="0" cellspacing="0" cellpadding="0">

<tr class="">

<td class="type">
<div>
<select name="type[<?php echo $key; ?>]">
<?php foreach($this->opts as $okey => $opt): ?>
<option value="<?php echo $okey; ?>" <?php if($okey == $field->type): ?> selected="selected"<?php endif; ?>><?php echo $opt; ?></option>
<?php endforeach; ?>
</select>
</div>
</td>

<td class="ftitle">
<div>
<input name="title[<?php echo $key; ?>]" type="text" value="<?php echo $field->title; ?>" />
</div>
</td>

<td class="mandatory">
<div>
<?php echo $this->formHidden("mandatory[{$key}]", 0); ?>
<?php echo $this->formCheckbox("mandatory[{$key}]", 1, array('checked' => $field->mandatory)); ?>
</div>
</td>

<td class="options">
<div>
<?php echo $this->formTextarea("options[{$key}]", $field->options, array('rows' => 3, 'cols' => 15)); ?>
</div>
</td>

<td class="actions">
<div>
<a class="emerald-confirm field-delete" href="<?php echo $this->url(array('module' => 'em-admin', 'controller' => 'form', 'action' => 'field-delete', 'id' => $field->id), 'default', true); ?>"><?php echo $this->translate('Delete'); ?></a>
</div>
</td>

</tr>
</table>
</div>
<?php endforeach; ?>
</div>


<p>
<button type="submit" class="submit niceButton"><?php echo $this->translate('Submit'); ?></button>
</p>

</form>

</div>