<form id="formcontent_edit" method="post" action="/admin/formcontent/save/page_id/<?php echo $this->item->page_id; ?>">

<label for="form_id"><?php echo $this->translate('Name'); ?></label>
<?php echo $this->formSelect('form_id', $this->item->form_id, array('class' => 'w33'), $this->form_id_options); ?>

<label for="email_subject"><?php echo $this->translate('Subject'); ?></label>
<?php echo $this->formText('email_subject', $this->item->email_subject, array('class' => 'w33')); ?>

<label for="email_from"><?php echo $this->translate('Email sender'); ?></label>
<?php echo $this->formText('email_from', $this->item->email_from, array('class' => 'w33')); ?>

<label for="email_to"><?php echo $this->translate('E-mail receiver'); ?></label>
<?php echo $this->formText('email_to', $this->item->email_to, array('class' => 'w33')); ?>

<label for="redirect_page_id"><?php echo $this->translate('Redirected page ID'); ?></label>
<?php echo $this->formText('redirect_page_id', $this->item->redirect_page_id, array('class' => 'w33')); ?>

<p>
<?php echo $this->formHidden('form_lock', 0); ?>
<?php echo $this->formCheckbox('form_lock', 1, array('checked' => $this->item->form_lock)); ?> <?php echo $this->translate('Lock form'); ?>
</p>

<p>
<?php echo $this->formButton('submiter', $this->translate('Submit'), array('type' => 'submit')); ?>
</p>

</form>


