<h1><?php echo $this->translate('About Emerald'); ?></h1>

<h2>Development lead</h2>

<ul>
<li>pekkis (Mikko Forsström)</li>
</ul>

<h2>Contributors</h2>

<ul>
<li>Mikko Hämäläinen</li>
<li>Petri Heinonen</li>
<li>Mikko Hirvonen</li>
<li>Petri Mahanen</li>
</ul>

<h2>Corporate sponsors</h2>

<ul>
<li>Foolabs Ltd</li>
<li>Brain Alliance Ltd</li>
</ul>


<h2><?php echo $this->translate('Software versions'); ?></h2>

<p>
<strong><?php echo $this->translate('Emerald Framework version'); ?>:</strong> <?php print Emerald_Version::VERSION; ?><br />
<strong><?php echo $this->translate('Zend Framework version'); ?>:</strong> <?php print Zend_Version::VERSION; ?>
</p>
