<?php echo $this->htmlcontent->content; ?>

<?php if($this->writable): ?>
<div class="adminControl">
<a
id="htmlcontent_edit"
class="popup popup_large popup_resizable popup_scrollbars" 
href="<?php echo $this->url(array('module' => 'core', 'controller' => 'htmlcontent', 'action' => 'edit', 'page_id' => $this->htmlcontent->page_id, 'block_id' => $this->htmlcontent->block_id)); ?>">
<?php echo $this->translate('common/edit'); ?>
</a>
</div>
<?php endif; ?>