<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>emerald CMS</title>
				
		<?php		
	 
		$this->jQuery()->enable()->uiEnable();
		$this->jQuery()->addStylesheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/smoothness/jquery-ui.css');
		Emerald_Js::addAdminScripts($this);
		$this->headLink()->prependStylesheet('/lib/css/admin/emerald_admin.css');
		
		$this->headScript()->appendFile('/lib/js/admin/login.js');
		$this->headLink()->appendStylesheet('/lib/css/admin/login.css');
						
		?>
				
		<?php echo $this->jQuery(); ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headScript(); ?>
	</head>

	<body>


		<div id="loginBoxContainer">
		
		
		<div id="loginBox">
		<div id="loginBoxContent">
		
		
		
		<form id="login">
		
		<div id="messages">
		<noscript><?php echo $this->translate('common/error_javascript_required'); ?></noscript>
		</div>

		<div class="input">
		<label for="locale"><?php echo $this->translate('Select language'); ?></label>
		<?php echo $this->formSelect('locale', $this->locale, array('disabled' => 'disabled'), $this->adminLocales); ?>
		</div>
	
		<div class="input">
		<label for="foo"><?php echo $this->translate('E-mail'); ?></label>		
		<input disabled="disabled" id="foo" name="foo" type="text" />
		</div>

		<div class="input">
		<label for="bar"><?php echo $this->translate('Password'); ?></label>
		<input disabled="disabled" id="bar" name="bar" type="password" />
		</div>
				
		<button id="submiter" disabled="disabled" type="submit"><?php echo $this->translate('Submit'); ?></button>
						
		</form>
		</div>
		</div>
		</div>
		
	</body>
</html>