<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<?php echo $this->headMeta(); ?>
<?php print $this->headTitle(); ?>

<script type="text/javascript" src="/lib/js/jquery/jquery.js"></script>
<script type="text/javascript">
var $j = jQuery.noConflict();
</script>
<script type="text/javascript" src="/lib/js/jquery/dimensions/jquery.dimensions.min.js"></script>
	
	<link rel="stylesheet" href="/data/css/customer.css" />
	
	<?php echo $this->headLink(); ?>
	<?php echo $this->headScript(); ?>

</head>
<body>
<div id="wrapper">
	<div id="header" class="container">
		<div id="logo">
			<h1><a href="http://drkobros.com/emerald-cms">Emerald CMS</a></h1>
			<p>
			A <a href="http://drkobros.com/">Dr. Kobros</a> project
			</p>
		</div>
		<div id="banner"><img src="/file/render/id/75" width="667" height="118" alt="" /></div>
	</div>
	
	<div id="menu" class="container">
	<?php echo $this->shard($this->page, "Menu", array('a' => 'index',"extended"=>1)); ?>
	</div>
	
	<div id="top-bar" class="container">
		<div class="bar">
			<div class="text">Aliquam sit amet veroeros dolore sed tempus nullam</div>
			<div id="search">
				<form method="get" action="">
					<fieldset>
						<input type="text" name="query" value="" class="input-text" />
						<input type="submit" value="Search" class="input-submit" />
					</fieldset>
				</form>
			</div>
		</div>
	</div>
	
	<div id="page" class="container">
	<?php echo $this->layout()->content; ?>	
	</div>
</div>
<div id="footer" class="container">
	<p>(c) 2009 Sitename.com. Design by <a href="http://www.nodethirtythree.com/">nodethirtythree</a> + <a href="http://www.freecsstemplates.org/">Free CSS Templates</a></p>
</div>
</body>
</html>
