<?php echo $this->doctype('XHTML1_TRANSITIONAL'); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<?php 
		$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');
		$this->headLink(array('href' => '/lib/emerald-icon.png', 'rel' => 'icon', 'type' => 'image/png'));
		$this->headTitle()->setSeparator(' - ')->append("Emerald");
		$this->jQuery()->enable()->uiEnable();
		$this->jQuery()->addJavascriptFile("/lib/emerald.js");
		// $this->headLink()->prependStylesheet('/lib/css/admin/emerald_popup.css');
		$this->jQuery()->addStylesheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/smoothness/jquery-ui.css');
		
		$this->headLink()->prependStylesheet('/lib/admin/main.css');

		// $this->headLink()->prependStylesheet('http://yui.yahooapis.com/3.0.0/build/cssbase/base-min.css');
		// $this->headLink()->prependStylesheet('http://yui.yahooapis.com/3.0.0/build/cssreset/reset-min.css');
			
		
		$this->headScript()->prependFile('/core/langlib/index/locale/' . Zend_Registry::get('Zend_Locale') . '/format/js');
		?>
		
		
		
		<?php echo $this->headLink(); ?>
		<?php echo $this->jQuery(); ?>
		<?php echo $this->headScript(); ?>
		
		
		<?php echo $this->headTitle(); ?>
	</head>

	<body>
	
	<div id="loading" style="display: none;">
		<img src="/lib/ajax-loader.gif" class="emerald-icon" />
	</div>
	
	<div id="wrapper">
		<div id="header">
			<div id="logo">
				<?php $cusr = Zend_Registry::get('Emerald_User'); ?> 
				<h1><a href="<?php echo $this->url(array('module' => 'admin'), 'default', true); ?>">Emerald</a></h1>
				<h2><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'edit', 'id' => $cusr->id), 'default', true); ?>"><?php echo $cusr->email ?> :: <a href="<?php echo $this->url(array('module' => 'core', 'controller' => 'user', 'action' => 'logout'), 'default', true); ?>"><?php echo $this->translate('Logout'); ?></a></h2>
			</div>
			<div id="menu">
				<?php echo $this->navigation()->menu()->renderMenu($this->navigation, array('maxDepth' => 0)); ?>
			</div>
		</div>
	</div>	
			
	<div id="page">
	<div id="page-content">
		
		<div id="breadcrumbs">
		<?php echo $this->navigation()->breadcrumbs($this->navigation); ?>
		</div>
			
		<div id="message" title="Obs" class="ui-state-highlight ui-corner-all"> 
			<p></p>
		</div>
					
		<?php echo $this->layout()->content; ?>
				
	</div>
	</div>
	
	
	</body>
</html>
