<?php echo $this->doctype('XHTML1_TRANSITIONAL'); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>

		<?php echo $this->headTitle(); ?>

		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		
		<?php 
		$this->jQuery()->enable()->uiEnable();
		$this->jQuery()->addStylesheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/smoothness/jquery-ui.css');
				
		Emerald_Js::addAdminScripts($this);
		
		$this->headLink()->prependStylesheet('/lib/css/admin/emerald_admin.css');
		
		$this->headScript()->prependFile('/admin/langlib/js/id/' . Zend_Registry::get('Zend_Locale'));
		
		?>
				
		
		<?php echo $this->headLink(); ?>
		<?php echo $this->jQuery(); ?>
		<?php echo $this->headScript(); ?>

		
	</head>

	<body>
		
		<?php echo $this->layout()->content; ?>

	</body>
</html>