<h1>{l:shard/calendar/edit}</h1>

<form id="edit" method="post" action="/admin/calendar/save/id/<?php echo $this->calendar->id; ?>">

<label for="title">{l:shard/calendar/prop/default_date}</label>
<?php echo $this->formText('default_date', $this->calendar->default_date, array('class' => 'w50')); ?>

<p>
<?php echo $this->formButton('submiter', '{l:common/submit}', array('type' => 'submit')); ?>
</p>

</form>
