<h1><?php echo $this->translate('Language library'); ?></h1>

<p>
	<a href="/admin/langlib/dump"><?php echo $this->translate('Gimme a current dumpsta'); ?></a>
</p>

<form method="post" action="/admin/langlib/create">

<fieldset>
<legend><?php echo $this->translate('Create a new language path'); ?></legend>

<label for="path">path</label>
<input class="w33" type="text" name="path" id="path" />

<label for="fi">fi</label>
<input class="w33" type="text" name="fi" id="fi" />

<label for="en">en</label>
<input class="w33" type="text" name="en" id="en" />

<p>
<button type="submit" class="submit niceButton"><?php echo $this->translate('Submit'); ?></button>
</p>

</fieldset>

</form>


<fieldset>
<legend><?php echo $this->translate('Language paths in library'); ?></legend>

<table border="1" width="100%" cellspacing="2" cellpadding="2">
<tr>
	<th>path</th>
	<th>fi</th>
	<th>en</th>
</tr>

<?php foreach($this->entries as $entry): ?>
<tr>
	<td><a href="/admin/langlib/edit/id/<?php echo $entry->id; ?>"><?php echo $entry->path; ?></a></td>
	<td><?php echo $entry->fi; ?></td>
	<td><?php echo $entry->en; ?></td>
</tr>
<?php endforeach; ?>



</table>




</fieldset>