<h1><?php echo $this->translate('shard/news/channel/edit'); ?></h1>

<form id="edit" method="post" action="/emerald-admin/newschannel/save/id/<?php echo $this->channel->id; ?>">

<label for="title"><?php echo $this->translate('shard/news/channel/title'); ?></label>
<?php echo $this->formText('title', $this->channel->title, array('class' => 'w50')); ?>

<label for="description"><?php echo $this->translate('shard/news/channel/description'); ?></label>
<?php echo $this->formTextarea('description', $this->channel->description, array('rows' => 6)); ?>

<label for="default_months_valid"><?php echo $this->translate('shard/news/channel/link_readmore'); ?></label>
<?php echo $this->formText('link_readmore', $this->channel->link_readmore, array('class' => 'w50')); ?>

<label for="items_per_page"><?php echo $this->translate('shard/news/channel/items_per_page'); ?></label>
<?php echo $this->formSelect('items_per_page', $this->channel->items_per_page, null, array(1=>1, 2=>2, 3=>3, 4=>4,5=>5,6=>6,7=>7,8=>8,9=>9,10=>10,11=>11,12=>12,13=>13,14=>14,15=>15,16=>16,17=>17,18=>18,19=>19,20=>20)); ?>

<label for="default_months_valid"><?php echo $this->translate('shard/news/channel/default_months_valid'); ?></label>
<?php echo $this->formSelect('default_months_valid', $this->channel->default_months_valid, null, array(1=>1, 2=>2, 4=>4, 8=>8, 12=>12, 24=>24, 36=>36)); ?>

<p>

<?php echo $this->formHidden('allow_syndication', 0); ?>
<?php echo $this->formCheckbox('allow_syndication', 1, array('checked' => $this->channel->allow_syndication)); ?> <?php echo $this->translate('shard/news/channel/allow_syndication'); ?>
</p>

<p>
<?php echo $this->formButton('submiter', $this->translate('common/submit'), array('type' => 'submit')); ?>
</p>

</form>
