<?php 
$this->headTitle()->append('Locales');
$this->headScript()->appendFile(EMERALD_URL_BASE_LIB . '/lib/admin/locale/index.js');
$this->headLink()->appendStylesheet(EMERALD_URL_BASE_LIB . '/lib/admin/locale/index.css');
?>

<h1><?php echo $this->translate('Locales'); ?></h1>


<div class="box">

<h2><?php echo $this->translate('Selected locales'); ?></h2>

<table class="w100">
<thead>
	<tr>
		<th><?php echo $this->translate('Locale'); ?></th>
		<th><?php echo $this->translate('Actions'); ?></th>
	</tr>
</thead>
<tbody>
<?php foreach($this->locales as $locale): ?>
<tr>
	<td>
		<?php echo $locale->locale; ?>
	</td>
	<td>
		<a href="<?php echo $this->url(array('action' => 'edit', 'id' => $locale->locale)); ?>"><?php echo $this->translate('Edit'); ?></a> |
		<a class="emerald-confirm locale-delete" href="<?php echo $this->url(array('action' => 'delete', 'id' => $locale->locale)); ?>"><?php echo $this->translate('Delete'); ?></a>
	</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>


<h2><?php echo $this->translate('Add new locales'); ?></h2>

<?php echo $this->form; ?>

</div>