<?php
$this->headTitle("Edit html content")->headTitle($this->page->title);

$this->emerald()->addTinyMCE();

$this->headScript()->appendFile(EMERALD_URL_BASE_LIB . "/lib/em-core/html-content/edit.js");

$this->layout()->setLayout('emerald-plain');

?>

<h2><?php echo $this->translate('Edit html content'); ?></h2>

<?php echo $this->form; ?>

<script type="text/javascript">
var beautifurl = Emerald.url('/<?php echo $this->page->beautifurl; ?>');

</script>

