<?php if($this->writable): ?>
<div class="adminControl">
<a id="htmlcontent_edit" class="popup popup_large popup_resizable popup_scrollbars" href="/emerald-admin/login/edit/page_id/<?php echo $this->page->id; ?>"><?php echo $this->translate('shard/formcontent/edit'); ?></a>
</div>
<?php endif; ?>

<?php if($this->user->id == Emerald_User::USER_ANONYMOUS): ?>

<?php $this->headScript()->appendFile('/lib/js/shard/login/page.js'); ?>

<div id="loginBoxContainer">
<div id="loginBox">
<div id="loginBoxContent">

<form id="login">

<input type="hidden" id="redirect_url" value="/<?php echo $this->redirectUrl; ?>" />

<div id="messages">
</div>

<label for="foo"><?php echo $this->translate('common/email'); ?></label>		
<input id="foo" name="foo" type="text" />

<label for="bar"><?php echo $this->translate('common/password'); ?></label>
<input id="bar" name="bar" type="password" />
		
<button id="submiter" type="submit"><?php echo $this->translate('common/submit'); ?></button>
				
</form>
</div>
</div>
</div>

<?php else: ?>

<p>
<a href="/logout"><?php echo $this->translate('common/logout'); ?></a>
</p>

<?php endif; ?>