<h1><?php echo $this->translate('Settings'); ?></h1>

<div id="container-1">

<ul>
	<li class="ui-tabs-nav-item"><a href="#fragment-applicationOptions"><span><?php echo $this->translate('Application'); ?></span></a></li>
	<?php foreach($this->locales as $locale): ?>
	
	<?php $this->workLocale->setLocale($locale->locale); ?>
	
	<?php 
	$localeName = $this->locale->getTranslation($this->workLocale->getLanguage(), 'language');
	if($this->workLocale->getRegion()) $localeName .= ", " . $this->locale->getTranslation($this->workLocale->getRegion(), 'country');	
	?>
	<li class="ui-tabs-nav-item"><a href="#fragment-localeOptions-<?php print $locale->locale; ?>"><span><?php echo $this->translate('Locale'); ?>: <?php print $localeName; ?></span></a></li>
	<?php endforeach; ?>
</ul>

<div id="fragment-applicationOptions">

<h2 class="hidden"><?php echo $this->translate('Application'); ?></h2>

<form id="saveApplicationFrm" method="post" action="/admin/options/save-application">


<table>
	<thead></thead>
	<tbody>
		<tr>
			<th><label for="default_locale"><?php echo $this->translate('Default language'); ?></label></th>
			<td>
				
				

	<select name="default_locale">
	<option value=""></option>
	<?php 
	foreach($this->locales as $wl):
		$this->workLocale->setLocale($wl->locale);
	?>
		<option 
			value="<?php echo $wl->locale ?>"
			<?php if($wl->locale == $this->application->getOption('default_locale')): ?>
				selected="selected"
			<?php endif; ?>
		>
		<?php 
		echo $this->locale->getTranslation($this->workLocale->getLanguage(), 'language');
		?>
		<?php if($this->workLocale->getRegion()) echo ", " . $this->locale->getTranslation($this->workLocale->getRegion(), 'country'); ?>
		</option>
	<?php endforeach; ?>
	</select>
	</td>
		</tr>
		
		<tr>
			<th><label for="google_analytics_id"><?php echo $this->translate('Google Analytics key'); ?></label></th>
			<td><?php echo $this->formText('google_analytics_id', $this->application->getOption('google_analytics_id')); ?></td>
		</tr>
				
	</tbody>
</table>

<p>
<button type="submit" class="submit niceButton"><?php echo $this->translate('Save'); ?></button>
</p>

</form>

</div>

<?php foreach($this->locales as $locale): ?>

<div id="fragment-localeOptions-<?php print $locale->locale; ?>">

<form id="saveLocaleFrm-<?php print $locale->locale; ?>" method="post" action="/admin/options/save-locale">

<input type="hidden" name="locale" value="<?php print $locale->locale; ?>" />

<table>
	<thead></thead>
	<tbody>
		<tr>
			<th><label for="title"><?php echo $this->translate('Title (in browser title bar)'); ?></label></th>
			<td><?php echo $this->formText('title', $locale->getOption('title')); ?></td>
		</tr>
	</tbody>
</table>

<p>
<button type="submit" class="submit niceButton"><?php echo $this->translate('Save'); ?></button>
</p>

</form>

</div>


<?php endforeach; ?>

	