		<div id="content">
			<div class="post">
				<h2 class="title"><a href="#">TerraFirma2 by NodeThirtyThree + FCT</a></h2>
				<p class="date">Posted on October 1, 2009</p>
				<div class="entry"> <img src="images/img02.jpg" width="132" height="122" alt="" class="border alignleft" />
					<p>This is <strong>TerraFirma2</strong>, a free template by <a href="http://www.nodethirtythree.com/">nodethirtythree</a> and <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.  This template is released under the <a href="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution</a> license so use it however you like, just keep the footer links back to our sites. The photos used in this design are from <a href="http://www.pdphoto.org/">PDPhoto.org</a>. Check out my other work at <a href="http://www.nodethirtythree.com/">my site</a> or follow me on <a href="http://twitter.com/nodethirtythree">Twitter</a>. Have fun.</p>
				</div>
				<div class="meta">
					<p class="tags">Tags: <a href="#">Internet</a>, <a href="#">Free Templates</a>, <a href="#">Web Design</a></p>
					<p class="links"><a href="#" class="comments">Comments (64)</a> <a href="#" class="more">More</a></p>
				</div>
			</div>
			<div class="post">
				<h2 class="title"><a href="#">Lorem ipsum dolor sit amet</a></h2>
				<p class="date">Posted on September 29, 2009</p>
				<div class="entry">
					<p>Faucibus non sit amet elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer placerat, dui sed posuere molestie, urna sapien porta purus, vel sodales ante erat sed arcu. Nunc semper, diam ut blandit elementum, ipsum purus vestibulum quam, sit amet auctor est nunc ut risus. Maecenas vitae justo sit amet erat congue aliquet molestie commodo odio. Praesent tempor pellentesque nibh.</p>
				</div>
				<div class="meta">
					<p class="tags">Tags: <a href="#">Internet</a>, <a href="#">Free Templates</a>, <a href="#">Web Design</a></p>
					<p class="links"><a href="#" class="comments">Comments (32)</a> <a href="#" class="more">More</a></p>
				</div>
			</div>
		</div>
		
		<div id="sidebar">
			<ul>
				<li>	
				<?php echo $this->shard($this->page, 'Htmlcontent', array('a' => 'index', 'block_id' => 2)); ?>
				</li>
				
				<li>	
				<?php echo $this->shard($this->page, 'Htmlcontent', array('a' => 'index', 'block_id' => 3)); ?>
				</li>
								
			</ul>
			
		</div>
		
		<div class="clearfix">&nbsp;</div>
		
		<div id="footer-bar" class="two-cols">
			<div class="col1">
				<h2>Aliquam sit amet veroeros</h2>
				<p>Faucibus non sit amet elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer placerat, dui sed posuere molestie, urna sapien porta purus, vel sodales ante erat sed arcu. Nunc semper, diam ut blandit elementum, ipsum purus vestibulum quam, sit amet auctor est ut risus. Maecenas sed dolore.</p>
			</div>
			<div class="col2">
				<ul>
					<li><a href="#">Faucibus non sit amet elit nulla</a></li>
					<li><a href="#">Consectetur adipiscing elit integer</a></li>
					<li><a href="#">Placerat dui sed posuere molestie</a></li>
					<li><a href="#">Urna sapien porta purus vel</a></li>
				</ul>
			</div>
			<div class="clearfix">&nbsp;</div>
		</div>








