<?php if($this->writable) { $this->headScript()->appendFile(EMERALD_URL_BASE . "/lib/core/news/index.js"); } ?>

<div class="news-channel" id="news-channel-page-<?php echo $this->channel->page_id; ?>">

<?php if($this->writable): ?>
	<div class="emerald-controls emerald-controls-heavy">
	<a id="newschannel-edit" class="emerald-popup popup-large popup-resizable popup-scrollbars"
	href="<?php echo $this->url(array('module' => 'core', 'controller' => 'news-channel', 'action' => 'edit', 'id' => $this->channel->id), 'default', true); ?>"><?php echo $this->translate('Edit newschannel'); ?></a>
	 | <a id="newsitem-add" class="emerald-popup popup-large popup-resizable popup-scrollbars"
	 href="<?php echo $this->url(array('module' => 'core', 'controller' => 'news-channel', 'action' => 'add-item', 'id' => $this->channel->id), 'default', true); ?>">
	 <?php echo $this->translate('Add newsitem'); ?>
	 </a>
	</div>
<?php endif; ?>

<?php echo $this->paginationControl($this->news, 'Sliding', 'news/pagination.phtml', array('page' => $this->page)); ?>

<?php foreach($this->news as $item): ?>

<?php $date = new Zend_Date($item->valid_start, Zend_Date::ISO_8601); ?>

<div class="news-item <?php if(!$item->isValid()): ?> emerald-invisible news-item-invalid <?php endif; ?>">

	<h2>
	<?php echo $date->get(Zend_Date::DATETIME_SHORT, $this->page->getLocale()) ?>: 
	<?php echo $item->title; ?>
	</h2>
	
	<div class="description">
	<?php echo $item->description; ?>
	</div>
	
	<p>
		<a href="<?php echo EMERALD_URL_BASE . '/'. $this->page->beautifurl; ?>?a=view&amp;id=<?php echo $item->id; ?>"><?php echo $this->channel->link_readmore; ?></a>
	</p>
	
<?php if($this->writable): ?>
	<div class="emerald-controls emerald-controls-light">
	<a id="newsitem-edit" class="emerald-popup popup-large popup-resizable popup-scrollbars" href="<?php echo $this->url(array('module' => 'core', 'controller' => 'news-item', 'action' => 'edit', 'id' => $item->id), 'default', true); ?>"><?php echo $this->translate('Edit'); ?></a> | <a class="emerald-confirm news-item-delete" href="<?php echo $this->url(array('module' => 'core', 'controller' => 'news-item', 'action' => 'delete', 'id' => $item->id), 'default', true); ?>"><?php echo $this->translate('Delete'); ?></a>
	</div>

	<?php endif; ?>	
	
</div>

<?php endforeach; ?>

	<?php if($this->writable): ?>

	<div class="emerald-htmlcontent-locales">
	
	<?php
	$model = new Core_Model_Page();
	$siblings = $model->findSiblings($this->page);
	?>
	
	<p><?php echo $this->translate('This page in different locales'); ?></p>
	<ul>
	<?php foreach($siblings as $sibling): ?>
	<li><a href="<?php echo EMERALD_URL_BASE; ?>/<?php echo $sibling->beautifurl; ?>"><?php echo $sibling->title; ?></a></li>
	<?php endforeach; ?>
	</ul>
	</div>
	
	<?php endif; ?>


<?php echo $this->paginationControl($this->news, 'Sliding', 'news/pagination.phtml', array('page' => $this->page)); ?>

<?php if($this->channel->allow_syndication): ?>
<p>
<a href="?format=xml">
	<img alt="<?php echo $this->translate('RSS-feed'); ?>" title="<?php echo $this->translate('RSS-feed'); ?>" src="<?php echo EMERALD_URL_BASE; ?>/lib/core/news/feed-icon-28x28.png" />
</a>
</p>
<?php endif; ?>



</div>
